[project]
name = "quantnetx"
version = "0.1.0"
description = "Bitcoin Risk Metric Analysis"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = ">=3.9"
numpy = ">=1.24"
pandas = ">=2.0"
scipy = ">=1.10"
requests = ">=2.28"
